### ISSUE TITLE
improvement suggestion

### ISSUE THREAD

**Issue by rafaminos** [covid-19-Re/dailyRe-Data#1]
would you be able to provide a big csv aggregating all the csv file (except data sources) in https://github.com/covid-19-Re/dailyRe-Data ?

thanks

**Comment by dcangst** [comment]
hey, thanks for your comment. 

you can easily and quickly get a complete csv using any scripting language. here's an example in `bash`:

```bash
{head -1 CHE-estimates.csv; sed 1d *-estimates.csv} > GLOBAL-estimates.csv
```

(first command doesn't need to be CHE, we just need the header (which is the same in all files))

Uploading this file would duplicate all the data and inflate the size of this repo (a file with all data weighs about 21mb atm.)

**Comment by rafaminos** [comment]
thanks
