### ISSUE TITLE
CHE data resets to older data over weekends

### ISSUE THREAD

**Issue by dr-itz** [covid-19-Re/dailyRe-Data#3]
e.g. the latest datapoint for CHE is `CHE,2021-06-17,0.51,0.68,0.34` while e.g. on Thursday more recent data was available.

https://github.com/covid-19-Re/dailyRe-Data/commit/4d9d920c6a5e27474c4095481d286bc267619f6b shows "15,151 additions, 15,631 " for `CHE-confCasesSWestimates.csv ` which is a net loss of 480 lines

**Comment by dcangst** [comment]
Thanks for spotting and reporting this problem! 
The cause was an oversight in our update job & that we don't actually get new data on a weekend. This meant that old data was uploaded. I reverted the data to the most recent estimates (from last Friday, 643382d).
